const fs = require('fs');
const path = require('path');

const exampleHtmlPath = '/Users/nc8/Library/Application Support/Open Design/namespaces/release-stable/data/projects/8ee9ca70-9a63-4381-9400-26d98568baf1/.od-skills/dashboard-ui-glass-37d856f48b/example.html';
const outputPath = path.join(__dirname, '../src/assets/avatars.js');

try {
  const content = fs.readFileSync(exampleHtmlPath, 'utf8');
  
  // Use regex to find all matches of data:image/svg+xml;base64,... in example.html
  const regex = /data:image\/svg\+xml;base64,[A-Za-z0-9+/=]+/g;
  const matches = content.match(regex) || [];
  
  console.log(`Found ${matches.length} avatar matches in example.html.`);
  
  // Keep unique ones
  const uniqueAvatars = Array.from(new Set(matches));
  console.log(`Extracted ${uniqueAvatars.length} unique avatars.`);
  
  // Generate avatars.js
  const fileContent = `// Auto-generated by scripts/extract-avatars.cjs\n` +
    `// Unique inline base64 SVG avatars extracted from example.html\n\n` +
    `export const AVATARS = [\n` +
    uniqueAvatars.map((url, i) => `  // Avatar ${i + 1}\n  "${url}"`).join(',\n') +
    `\n];\n\n` +
    `// Named exports for specific roles in the layout\n` +
    `export const CURRENT_USER = AVATARS[0] || "";\n` +
    `export const MEETING_HOST = AVATARS[1] || "";\n` +
    `export const SPEAKER = AVATARS[2] || "";\n` +
    `export const P1 = AVATARS[3] || "";\n` +
    `export const P2 = AVATARS[4] || "";\n` +
    `export const P3 = AVATARS[5] || "";\n` +
    `export const ALICE_AV = AVATARS[6] || "";\n`;
    
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, fileContent, 'utf8');
  console.log(`Successfully wrote extracted avatars to ${outputPath}`);
} catch (err) {
  console.error("Error extracting avatars:", err);
  process.exit(1);
}
